# Site settings
title: Max Heinritz
url: http://maxheinritz.com
desc: Max Heinritz's personal website and project portfolio.
collections:
  notes:
    output: true
  projects:
    output: true

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

theme: minima
exclude:
  - README.md
  - CNAME
  - Gemfile
  - Gemfile.lock

defaults:
  -
    scope:
      path: "storage/**/*"
    values:
      sitemap: false
  -
    scope:
      path: "images/**/*"
    values:
      sitemap: false

plugins:
  - jekyll-sitemap
