# Site settings
title: Max Heinritz
url: http://maxheinritz.com
collections:
  projects:
    output: true

# Build settings
markdown: kramdown
theme: minima
exclude:
  - README.md
  - CNAME
  - Gemfile
  - Gemfile.lock
