# Site settings
title: Max Heinritz
url: http://maxheinritz.com
collections:
  projects:
    output: true

# Build settings
markdown: kramdown
theme: minima
exclude:
  - README.md
  - CNAME
  - Gemfile
  - Gemfile.lock

defaults:
  -
    scope:
      path: "storage/**/*"
    values:
      sitemap: false
  -
    scope:
      path: "images/**/*"
    values:
      sitemap: false

plugins:
  - jekyll-sitemap
